# Build CI Pipelines

name: Build Nodejs ci Pipeline
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@2

      - name: actions/setup-node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm test

      - name: Build
        run: npm run build