name: CODE SCANNING

on: [workflow_dispatch, push]

jobs:
    SonarCloud:
     name: SonarCloud
     runs-on: ubuntu-latest
     steps: 
      -  name: fetching code
         uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
            node-version: 18
        
      - name: Install dependencies (optional, for test coverage or linting)
        run: npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
            GITHUB_TOKEN: ${{secrets.ACCOUNT_TOKEN}}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{secrets.SONAR_TOKEN}} 

      - name: Notify Slack
        if: always()   # Run this step even if previous steps fail
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "SonarCloud scan completed for ${{ github.repository }} on commit ${{ github.sha }} by ${{ github.actor }}."
          SLACK_COLOR: good


    

