name: CODE SCANNING

on: [workflow_dispatch, push]

jobs:
    SonarCloud:
     name: SonarCloud
     runs-on: ubuntu-latest
     steps: 
      -  name: fetching code
         uses: actions/checkout@v3
      
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Create sample report
        run: |
          mkdir report
          echo "Workflow finished at $(date)" > report/info.txt

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
         name: sample-report
         path: report/
        
      - name: Install dependencies (optional, for test coverage or linting)
        run: npm install
      

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
            GITHUB_TOKEN: ${{secrets.ACCOUNT_TOKEN}}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{secrets.SONAR_TOKEN}} 

      - name: Notify Slack
        if: always()   # Run this step even if previous steps fail
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "SonarCloud scan completed for ${{ github.repository }} on commit ${{ github.sha }} by ${{ github.actor }}."
          SLACK_COLOR: good

      - name: Send Email Notification
        if: always ()
        uses: dawidd6/action-send-mail@v3
        with:
         server_address: smtp.gmail.com # SMTP server address, e.g. smtp.gmail.com
         server_port: 465      # SMTP port, usually 465 (SSL) or 587 (TLS)
         username: ${{ secrets.SMTP_USERNAME }}     # Your email address used for SMTP login
         password: ${{ secrets.SMTP_PASSWORD }}     # Password or app-specific password for SMTP login
         subject: GitHub Actions - Workflow Failed   # Email subject line
         body: "The workflow for repo ${{ github.repository }} failed on commit ${{ github.sha }}."  # Email body text
         to: dvop.omer@gmail.com                  # Recipient email address (who will receive the email)
         from: Github Actions

